version: "3.8"
services:
  app:
    build:
      context: .
    volumes:
      - .:/movies-to-watch-frontend
    ports:
      - 3000
    image: app:react
    container_name: react_container
    command: npm start